config/routes.rb
# frozen_string_literal: true

Koi::Engine.routes.draw do
  devise_for :admins, class_name:  "AdminUser",
                      controllers: {
                        passwords: "koi/passwords",
                        sessions:  "koi/sessions",
                      }

  resources :uploads, only: :create

  resources :assets
  resources :images
  resources :documents

  resources :translations, path: :site_settings do
    get :seed, on: :collection
  end
  resources :settings do
    put :update_multiple, on: :collection
  end
  resources :pages
  resources :url_rewrites
  resources :friendly_id_slugs
  resources :admins, path: :site_users
  resources :module_nav_items
  resources :folder_nav_items
  resources :alias_nav_items
  resources :resource_nav_items
  resources :nav_items do
    get :toggle, on: :member
    collection do
      get :sitemap
      post :savesort
    end
  end
  resources :navigation_menus do
    resources :navigation_links, as: :links, path: :links
  end

  post "clear-cache" => "application#clear_cache", :as => :clear_cache
  get  "help" => "application#help", :as => :help
  get  "dashboard" => "application#index", :as => :dashboard
  root to: "application#login"

  if Rails.env.development?
    get "/styleguide"           => "styleguide#index"
    get "/styleguide/:template" => "styleguide#show", template: /[-_a-z]+/
  end

  mount Flipper::UI.app(Flipper) => "flipper"
end

app/models/concerns/koi/model.rb
# frozen_string_literal: true

module Koi
  module Model
    extend ActiveSupport::Concern

    included do
      include Exportable
      include HasSettings
      include HasNavigation
      include HasCrud::ActiveRecord
    end
  end
end

app/models/koi/application_record.rb
# frozen_string_literal: true

module Koi
  class ApplicationRecord < ActiveRecord::Base
    include Koi::Model

    self.abstract_class = true
  end
end

app/controllers/koi/admin_crud_controller.rb
# frozen_string_literal: true

module Koi
  class AdminCrudController < Koi::ApplicationController
    KOI_PATH_HELPER_RE = /(\w+_|\b)koi_(\w+)_path$/.freeze

    helper :all
    has_crud admin: true
    defaults route_prefix: "admin"

    def index
      respond_to do |format|
        format.html
        format.js
        format.csv { respond_with_csv }
      end
    end

    protected

    def respond_to_missing?(key, include_private = false)
      KOI_PATH_HELPER_RE.match?(key) || super
    end

    # Matches missing route methods of the form (action_)?koi_(controller)_path,
    # and sends them to koi_engine instead.
    #
    # This is necessary because inherited_resources is resolving paths differently
    # depending on whether they belong to the koi_engine or not.
    #
    def method_missing(key, *sig, &blk)
      if (match = KOI_PATH_HELPER_RE.match(key))
        prefix, suffix = match.to_a.drop 1
        koi_engine.send :"#{prefix}#{suffix}_path", *sig, &blk
      else
        super
      end
    end
  end
end

app/controllers/koi/admin_resource_controller.rb
module Koi
  # Initialized by Koi::Resource::register
  class AdminResourceController < ActionController::Base
    layout 'koi/application'

    # See lib/koi/resource_actions.rb for actions
  end
end

app/controllers/koi/admins_controller.rb
# frozen_string_literal: true

module Koi
  class AdminsController < AdminCrudController
    defaults resource_class: AdminUser, route_prefix: ""

    def update_resource(object, attributes)
      if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
        object.update_without_password(*attributes)
      else
        object.update(*attributes)
      end
    end
  end
end

app/controllers/koi/alias_nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class AliasNavItemsController < NavItemsController
    defaults resource_class: AliasNavItem
  end
end

app/controllers/koi/application_controller.rb
# frozen_string_literal: true

module Koi
  class ApplicationController < ActionController::Base
    include HasCrud::ActionController
    include ExportableController

    helper :all
    layout :layout_by_resource
    before_action :authenticate_admin, except: :login
    before_action :set_navigation_menu, except: :login

    def login
      if admin_signed_in?
        redirect_to dashboard_path
      else
        redirect_to koi_engine.new_admin_session_path
      end
    end

    def clear_cache
      Rails.logger.warn("[CACHE CLEAR] - Cleaning entire cache manually by #{current_admin} request")
      Rails.cache.clear
      redirect_back(fallback_location: dashboard_path)
    end

    protected

    # FIXME: Hack to set layout for admin devise resources
    def layout_by_resource
      if devise_controller? && resource_name == :admin
        "koi/devise"
      else
        "koi/application"
      end
    end

    # FIXME: Hack to redirect back to admin after admin login
    def after_sign_in_path_for(resource_or_scope)
      resource_or_scope.is_a?(AdminUser) ? koi_engine.root_path : super
    end

    # FIXME: Hack to redirect back to admin after admin logout
    def after_sign_out_path_for(resource_or_scope)
      resource_or_scope == :admin ? koi_engine.root_path : super
    end

    def authenticate_admin
      redirect_to koi_engine.new_admin_session_path unless admin_signed_in?
    end

    def set_navigation_menu
      @navigation_menu = NavigationMenu.find_by(slug: "admin")
    end
  end
end

app/controllers/koi/assets_controller.rb
# frozen_string_literal: true

module Koi
  class AssetsController < AdminCrudController
    before_action :init

    layout "koi/assets"

    def index
      @assets = collection.newest_first.page(params[:page]).per(20)
      params[:asset] = { tag_list: [@tags] }
      super
    end

    def new
      @assets = collection.newest_first.page(params[:page]).per(20)
      params[:asset] = { tag_list: [@tags] }
      super
    end

    def show
      @assets = collection.newest_first.page(params[:page]).per(20)
    end

    def edit
      @assets = collection.newest_first.page(params[:page]).per(20)
    end

    def create
      super do |format|
        format.html { redirect_to resource_path(resource) }
        format.js { render plain: resource.id }
      end
    end

    def destroy
      super do |format|
        format.html { redirect_to new_resource_path }
        format.js
      end
    end

    # HELPERS ########################################################################################

    def redirect_path
      resource_path(resource)
    end

    def url_options
      super.reverse_merge(custom_url_options)
    end

    def custom_url_options
      @custom_url_options || {}
    end

    def custom_url_options=(options)
      @custom_url_options = (@custom_url_options || {}).merge(options) if options.is_a?(Hash)
    end

    protected

    def sort_column
      resource_class.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def collection
      return get_collection_ivar unless get_collection_ivar.nil?

      coll = end_of_association_chain
      coll = coll.unassociated
      coll = coll.search_data params[:search]
      coll = coll.tagged_with @tags if @tags.present?
      coll = coll.order "#{sort_column} #{sort_direction}"
      set_collection_ivar coll
    end

    def init
      @tags = params[:tags] || []
      @all_tags = resource_class.tag_counts_on(:tags).map(&:name)
      self.custom_url_options = { tags: @tags, CKEditorFuncNum: params[:CKEditorFuncNum] }
    end

    def create_resource(object)
      object.data = params[:file]
      object.data_name = params[:file].original_filename
      object.tag_list = params[:tag_list]
      object.save
    end
  end
end

app/controllers/koi/composable_contents_controller.rb
class Admin::PageContentsController < Koi::AdminCrudController
end

app/controllers/koi/composable_pages_controller.rb
module Koi
  class ComposablePagesController < AdminCrudController
  end
end

app/controllers/koi/crud_controller.rb
# frozen_string_literal: true

module Koi
  class CrudController < ActionController::Base # rubocop:disable Rails/ApplicationController
    include HasCrud::ActionController

    layout "application"
    has_crud
    defaults route_prefix: ""
  end
end

app/controllers/koi/documents_controller.rb
# frozen_string_literal: true

module Koi
  class DocumentsController < Koi::AssetsController
    defaults route_prefix: "", resource_class: Document

    def create
      create! do |success, failure|
        failure.html do
          logger.warn("[Asset Upload] - #{resource.errors.messages[:data].join(', ')}")
          render json: resource.errors, status: :unprocessable_entity
        end
        failure.js do
          logger.warn("[Asset Upload] - #{resource.errors.messages[:data].join(', ')}")
          render json: resource.errors, status: :unprocessable_entity
        end
        success.js { render plain: resource.id }
      end
    end
  end
end

app/controllers/koi/folder_nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class FolderNavItemsController < NavItemsController
    defaults resource_class: FolderNavItem
  end
end

app/controllers/koi/friendly_id_slugs_controller.rb
# frozen_string_literal: true

module Koi
  class FriendlyIdSlugsController < AdminCrudController
    defaults route_prefix: ""
  end
end

app/controllers/koi/images_controller.rb
# frozen_string_literal: true

module Koi
  class ImagesController < Koi::AssetsController
    defaults route_prefix: "", resource_class: Image
  end
end

app/controllers/koi/module_nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class ModuleNavItemsController < NavItemsController
    defaults resource_class: ModuleNavItem
  end
end

app/controllers/koi/nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class NavItemsController < AdminCrudController
    defaults route_prefix: ""
    custom_actions resource: :toggle

    def new
      @site_parent = NavItem.find(params[:site_parent])
      super
    end

    def create
      create! do |success, failure|
        success.html { redirect_to redirect_path }
        success.js
        failure.js
      end
    end

    def update
      update! do |success, failure|
        success.html { redirect_to redirect_path }
        success.js
        failure.js
      end
    end

    def destroy
      destroy! do |format|
        format.html { redirect_to redirect_path }
        format.js
      end
    end

    def sitemap
      @nav_items = NavItem.all
    end

    def savesort
      nodes = JSON.parse params[:set]

      nodes.map! do |node|
        node.each_with_object({}) do |(key, val), hash|
          hash[key.to_sym] = ActiveRecord::Base.connection.quote val
        end.reverse_merge parent_id: "NULL" # in case of `undefined` in which update below will fail
      end

      ids = nodes.pluck(:id)

      # mass update (should be abstracted)
      NavItem.connection.execute <<-SQL
        UPDATE nav_items
          SET lft = CASE id
                      #{nodes.map { |node| 'WHEN %<id>s THEN %<lft>s' % node }.join "\n"}
                    END,
              rgt = CASE id
                      #{nodes.map { |node| 'WHEN %<id>s THEN %<rgt>s' % node }.join "\n"}
                    END,
              parent_id = CASE id
                      #{nodes.map { |node| 'WHEN %<id>s THEN %<parent_id>s' % node }.join "\n"}
                    END#{'                    '}
        WHERE id in (#{ids.join ','})
      SQL
      render partial: "nav_item", locals: { nav_item: RootNavItem.root, level: 0 }
    end

    def sort_children(element, dbitem)
      prevchild = nil
      element["children"].each do |child|
        childitem = NavItem.find(child["id"])
        prevchild.nil? ? childitem.move_to_child_of(dbitem) : childitem.move_to_right_of(prevchild)
        sort_children(child, childitem) unless child["children"].nil?
        prevchild = childitem
      end
    end

    def toggle
      resource.toggle_hidden!
      respond_to do |format|
        format.html { redirect_path }
        format.js
      end
    end

    protected

    def redirect_path
      if params[:commit].eql?("Continue")
        edit_resource_url
      else
        sitemap_nav_items_path
      end
    end
  end
end

app/controllers/koi/navigation_links_controller.rb
# frozen_string_literal: true

module Koi
  class NavigationLinksController < Koi::ApplicationController
    before_action :set_menu
    before_action :set_link, except: %i[index new create]

    def index
      render locals: { links: @menu.navigation_links }
    end

    def new
      render locals: { link: @menu.navigation_links.build }
    end

    def create
      link = @menu.navigation_links.build(navigation_link_params)
      if link.save
        render :update, locals: { link: link, previous: NavigationLink.new }, notice: "Navigation link created"
      else
        render :new, status: :unprocessable_entity, locals: { link: link }
      end
    end

    def show; end

    def edit
      render locals: { link: @link }
    end

    # PATCH /admins/navigation_menu/:slug/navigation_link/:id
    def update
      @link.attributes = navigation_link_params

      if @link.valid?
        previous = @link
        @link    = @link.dup.tap(&:save!)
        render locals: { link: @link, previous: previous }, notice: "Navigation link updated"
      else
        render :edit, status: :unprocessable_entity, locals: { link: @link }
      end
    end

    private

    def navigation_link_params
      params.require(:navigation_link).permit(%i[title url visible new_tab])
    end

    def set_menu
      @menu = NavigationMenu.find_by!(slug: params[:navigation_menu_id])
    end

    def set_link
      @link = NavigationLink.find(params[:id])
    end
  end
end

app/controllers/koi/navigation_menus_controller.rb
class Koi::NavigationMenusController < Koi::ApplicationController
  include Katalyst::Tables::Backend

  def index
    sort, menus = table_sort(NavigationMenu.all)

    render locals: { menus: menus, sort: sort }
  end

  def new
    render locals: { menu: NavigationMenu.new }
  end

  def create
    menu = NavigationMenu.new(navigation_menu_params)

    if menu.save
      redirect_to menu, notice: "Navigation menu created"
    else
      render :new, locals: { menu: menu }, status: :unprocessable_entity
    end
  end

  def show
    menu = NavigationMenu.find_by!(slug: params[:id])

    render locals: { menu: menu }
  end

  # PATCH /admins/navigation_menus/:slug
  def update
    menu = NavigationMenu.find_by!(slug: params[:id])

    menu.attributes = navigation_params

    unless menu.valid?
      return render :show, locals: { menu: menu }, status: :unprocessable_entity
    end

    case params[:commit]
    when "publish"
      menu.save!
      menu.publish!
    when "save"
      menu.save!
    when "revert"
      menu.revert!
    end
    redirect_to menu
  end

  def destroy
    menu = NavigationMenu.find_by!(slug: params[:id])

    menu.destroy!

    redirect_to navigation_menus_path, notice: "Navigation menu destroyed"
  end

  private

  def navigation_menu_params
    params.require(:navigation_menu).permit(:title, :slug)
  end

  def navigation_params
    return {} if params[:navigation_menu].blank?

    params.require(:navigation_menu)
          .permit(navigation_links_attributes: [:id, :index, :depth])
  end
end

app/views/koi/nav_items/_advanced_form_fields.html.erb
<div class="inputs">
  <%= f.input :admin_url %>
  <%= f.input :key %>
  <%= f.input :setting_prefix %>
  <%= f.input :method, as: :string %>
</div>

app/views/koi/nav_items/_form_field_hidden.html.erb
<%= f.input attr, as: :hidden, wrapper: :koi, input_html: { value: (resource.parent_id || params[:site_parent] || @site_parent) } %>

app/views/koi/nav_items/_form_field_tree.html.erb
<%= f.input attr, as: :select, wrapper: :koi, collection: nested_set_options(NavItem, resource) {|i| "#{'-' * i.level} #{i.title}"} %>

app/views/koi/nav_items/_lock_sitemap.html.erb
<% panel_class ||= "" %>

<div class="panel__passive panel--padding sitemap--lock <%= panel_class %>">
  <div class="sitemap--lock--button">
    <button class="button__primary" data-sitemap-lock></button>
  </div>
  <div class="sitemap--lock--text">
    <p>Lock the drag and drop functionality of the sitemap while creating or editing your pages.</p>
  </div>
</div>

app/views/koi/nav_items/_modal_nav_item.html.erb
<%= render layout: "koi/shared/inline_lightbox", locals: { title: (resource.new_record? ? "Add #{resource_class.title}" : "Edit #{resource.title}"), inline_id: "modal_nav_item", no_hide: true, footer: capture { %>

  <div class="button-group">
    <div>
      <%= content_tag :button, "Save", type: "submit", name: "commit", value: "Save" , class: "button__save", form: "sitemap-modal-form" %>
    </div>
    <% unless resource.new_record? %>
      <div>
        <%= link_to "Delete", resource, data: { confirm: "Are you sure you want to delete this navigation item and all it's children? This will not delete the module or page it's associated to." }, method: :delete, remote: true, class: "button__cancel", form: "sitemap-modal-form"  %>
      </div>
    <% end %>
  </div>

<% } } do %>

  <%= simple_form_for resource, remote: true, html: { multipart: true, id: "sitemap-modal-form" } do |f| %>

    <div class="tabs" data-tabs="navitem_modal">
      <div class="tabs--links tabs--links__flush">
        <ul>
          <li>
            <a href="#tab_basic" class="tabs--link tabs--link__active" data-tab="tab_basic">Basic</a>
          </li>
          <% if current_admin.god? %>
            <li><a href="#tab_advanced" class="tabs--link" data-tab="tab_advanced">Advanced</a></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="tabs--panes tabs--panes__flush">
      <div class="tabs--pane tabs--pane__active" id="tab_basic" data-tab-for="tab_basic">
        <div class="inputs">
          <%= render "form_fields", f: f %>
        </div>
      </div>
      <% if current_admin.god? %>
        <div class="tabs--pane" id="tab_advanced" data-tab-for="tab_advanced">
          <%= render "advanced_form_fields", f: f %>
        </div>
      <% end %>
    </div>

    <div class="panel--padding panel--border-top">
      <p>
        <strong>Please note:</strong><br />
        Fields marked with an asterisk are required.
      </p>
    </div>

  <% end %>
<% end %>

app/views/koi/nav_items/_nav_item.html.erb
<%# cache "nav_item/admin/#{nav_item.id}-#{nav_item.updated_at}/sitemap", expires_in: 7.days do %>

  <%
    nav_item_type = nav_item.class.name.underscore.dasherize
    nav_item_id = nav_item.id
    nav_item_is_hidden = nav_item.is_hidden?
    is_root_nav_item = nav_item.is_a?(RootNavItem)
  %>

  <li id="nav-item-<%= nav_item.id %>"
      class="nav-item sitemap--group application id-<%= nav_item_id %>
             <%= "sortable" if nav_item.draggable? %>
             level-<%= level %>
             <%= 'is-hidden' if nav_item_is_hidden %>
             <%= " mjs-nestedSortable-expanded" if level.eql?(0) %>"
      data-type="<%= nav_item_type %>"
      data-id="<%= nav_item_id %>"
      data-left-ordinal="<%= nav_item.lft %>"
      data-right-ordinal="<%= nav_item.rgt %>"
    >

    <!-- zone provides hoverable space between elements so there are no dead-spots -->
    <div class="zone">
      <div class="nav-item--body">

        <% if Koi::Sitemap.toggles && !is_root_nav_item %>
          <span title="Click to show/hide children" class="disclose" data-node-id="<%= nav_item.id %>">
            <span class="ui-icon ui-icon-minusthick">Toggle</span>
          </span>
        <% end %>

        <div class="information <%= nav_item.is_what? %>">
          <% if level.eql?(0) %>
            Navigation Groups
          <% else %>

            <div class="nav-item--icon">
              <span class="<%= nav_item.is_what? %> icon" title="<%= nav_item.is_what? %>"></span>
            </div>

            <div class="nav-item--title">
              <% if nav_item.admin_url.blank? %>
                <%= nav_item.title %>
              <% else %>
                <%= link_to nav_item.title, nav_item.admin_url %>
              <% end %>
            </div>

            <% if nav_item_is_hidden %>
              <div class="nav-item--hidden" title="This item is hidden and will not appear in navigation">
                <%= icon("hidden") %>
              </div>
            <% end %>

            <% unless nav_item.key.blank? %>
              <div class="nav-item--key" title="<%= nav_item.key %>">
                <%= icon("key") %>
              </div>
            <% end %>

            <% if nav_item.link_to_first_child? %>
              <div class="nav-item--links-to-child" title="This navitem will link to it's first child">
                <%= icon("links_to_child") %>
              </div>
            <% end %>

          <% end %>
        </div>

        <div class="controls">
          <ul class="hoverable menu ui-nestedSortable-no-nesting">

            <% if is_root_nav_item %>
              <li>
                <button class="button__small button__primary" data-sitemap-open-all>Open all</button>
              </li>
              <li>
                <button class="button__small button__primary" data-sitemap-close-all>Close all</button>
              </li>
            <% end %>

            <%= content_tag :li, link_to("Modify", [:edit, nav_item], remote: true, class: "button__small button__primary", data: { disable_with: "Loading" }) unless is_root_nav_item %>

            <li class="has-menu">
              <a href="#" class="button__small button__primary">Add...</a>
              <ul class="vertical solid divided hoverable light-orange menu buttons">
                <%= content_tag :li, link_to("Module", new_module_nav_item_path(site_parent: nav_item.id), remote: true, class: "button__primary button__full button__small", data: { disable_with: "Loading" }) if current_admin.god? %>
                <%= content_tag :li, link_to("Alias" , new_alias_nav_item_path(site_parent: nav_item.id), remote: true, class: "button__primary button__full button__small", data: { disable_with: "Loading" }) %>
                <%= content_tag :li, link_to("Folder", new_folder_nav_item_path(site_parent: nav_item.id), remote: true, class: "button__primary button__full button__small", data: { disable_with: "Loading" }) %>
                <% Koi::Navigation.each do |model| %>
                  <%= content_tag :li, link_to(model.to_s, model.get_new_admin_url(site_parent: nav_item.id), class: "button__primary button__full button__small")  %>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <% unless nav_item.children.empty? %>
      <ol class="nav-items <%= "sitemap--root" if level.eql?(0) %>">
        <%= render partial: 'nav_item', collection: nav_item.children, as: :nav_item, locals: { level: level + 1 } %>
      </ol>
    <% end %>
  </li>

<%# end %>

app/views/koi/nav_items/create.js.erb
<% if resource.errors.any? %>

  // Replace the content of the current modal with the partial again in an errored state
  var currentId = $.magnificPopup.instance.currItem.inlineElement.attr("id");
  var $newContent = $("<%= escape_javascript render ("modal_nav_item") %>");
  $("#"+currentId).html("").append($newContent.children());

  // Open the first tab with errors
  var $firstErrorField = $(".lightbox--content .error-block").first()
  var $firstErroredTab = $firstErrorField.closest("[data-tab-for]");
  var firstErroredTabId = $firstErroredTab.attr("data-toggle");
  var $tabAnchorForFirstError = $(".lightbox--content [data-toggle-anchor=" + firstErroredTabId + "]");
  $tabAnchorForFirstError.click();

  // Resize lightbox
  Ornament.popupOpened(true);

<% else %>

  $.magnificPopup.close();

  var rendered = "<%= escape_javascript render("nav_item", nav_item: resource, level: resource.level) %>";
  
  var $parent = $ ("#nav-item-<%= resource.parent.id %>");
  var $children = $parent.children ("ol");

  if (! $children.length) {
    var $children = $("<ol />");
    $parent.append ($children);
  } 

  $children.append (rendered);

  // Show/hide toggles
  $parent.addClass("mjs-nestedSortable-branch mjs-nestedSortable-expanded");

  $ ("#nav-item-<%= resource.id %>").slideDown ().effect ("highlight", {}, 3000);

  Ornament.C.Sitemap.afterUpdate();

<% end %>

app/views/koi/nav_items/destroy.js.erb
$.magnificPopup.close();

$('#nav-item-<%= resource.id %>').fadeOut('slow', function(){
  var $oldNode = $(this);
  // Deal with show/hide toggles
  var $parent = $oldNode.parent("ol");
  $oldNode.remove();
  if($parent.children().length === 0) {
    $parent.parent("li").removeClass("mjs-nestedSortable-branch mjs-nestedSortable-expanded");
    $parent.remove();
  }
});

app/views/koi/nav_items/edit.js.erb
var popupOptions = $.extend({}, Ornament.popupOptions);
popupOptions.items = {
  src: "<%= escape_javascript render("modal_nav_item") %>",
}
$.magnificPopup.open(popupOptions);

app/views/koi/nav_items/new.js.erb
var popupOptions = $.extend({}, Ornament.popupOptions);
popupOptions.items = {
  src: "<%= escape_javascript render("modal_nav_item") %>",
}
$.magnificPopup.open(popupOptions);

app/views/koi/nav_items/sitemap.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "koi/nav_items" %>
<% end %>

<% content_for :title, "Sitemap" %>

<%= render "lock_sitemap", panel_class: "sitemap--lock__mobile" %>

<div class="sitemap application" data-uri-save="<%= koi_engine.savesort_nav_items_path %>">
  <ol>
    <%= render 'nav_item', nav_item: NavItem.root, level: 0 %>
  </ol>
</div>

<div id="modal-for-nav-item">&nbsp;</div>

<% content_for :side do %>

  <div class="content-spacing">

    <%= render "lock_sitemap", panel_class: "sitemap--lock__desktop" %>

    <h2 class="heading-two">Adding a page</h2>
    
    <p>To select a new page move your cursor over the item above or the folder the page should be part of. Roll over the 'add' link and select 'page' to add the page. </p>
    <p>After you have added the page, go back to the site map and move the page to the correct position.</p>
    <p>More information can be found in the <%= link_to "help section", koi_engine.help_path %>.</p>

  </div>

<% end %>

app/views/koi/nav_items/toggle.js.erb
$.magnificPopup.close();
$('#nav-item-<%= resource.id %> div:first').effect("highlight", {}, 3000);

app/views/koi/nav_items/update.js.erb
<% if resource.errors.any? %>

  var currentId = $.magnificPopup.instance.currItem.inlineElement.attr("id");
  var $newContent = $("<%= escape_javascript render ("modal_nav_item") %>");
  $("#"+currentId).html("").append($newContent.children());

  // Open the first tab with errors
  var $firstErrorField = $(".lightbox--content .error-block").first()
  var $firstErroredTab = $firstErrorField.closest("[data-tab-for]");
  var firstErroredTabId = $firstErroredTab.attr("data-toggle");
  var $tabAnchorForFirstError = $(".lightbox--content [data-toggle-anchor=" + firstErroredTabId + "]");
  $tabAnchorForFirstError.click();

  // Resize lightbox
  Ornament.popupOpened(true);

<% else %>
  $.magnificPopup.close();
  $("#nav-item-<%= resource.id %>").replaceWith("<%= escape_javascript render("nav_item", nav_item: resource, level: resource.level) %>");
  $("#nav-item-<%= resource.id %> div:first").effect("highlight", {}, 3000);
  Ornament.C.Sitemap.afterUpdate();
<% end %>