config/routes.rb
# frozen_string_literal: true

Koi::Engine.routes.draw do
  devise_for :admins, class_name:  "AdminUser",
                      controllers: {
                        passwords: "koi/passwords",
                        sessions:  "koi/sessions",
                      }

  resources :uploads, only: :create

  resources :assets
  resources :images
  resources :documents

  resources :translations, path: :site_settings do
    get :seed, on: :collection
  end
  resources :settings do
    put :update_multiple, on: :collection
  end
  resources :pages
  resources :url_rewrites
  resources :friendly_id_slugs
  resources :admins, path: :site_users
  resources :module_nav_items
  resources :folder_nav_items
  resources :alias_nav_items
  resources :resource_nav_items
  resources :nav_items do
    get :toggle, on: :member
    collection do
      get :sitemap
      post :savesort
    end
  end
  resources :navigation_menus do
    resources :navigation_links, as: :links, path: :links
  end

  post "clear-cache" => "application#clear_cache", :as => :clear_cache
  get  "help" => "application#help", :as => :help
  get  "dashboard" => "application#index", :as => :dashboard
  root to: "application#login"

  if Rails.env.development?
    get "/styleguide"           => "styleguide#index"
    get "/styleguide/:template" => "styleguide#show", template: /[-_a-z]+/
  end

  mount Flipper::UI.app(Flipper) => "flipper"
end

app/models/concerns/koi/model.rb
# frozen_string_literal: true

module Koi
  module Model
    extend ActiveSupport::Concern

    included do
      include Exportable
      include HasSettings
      include HasNavigation
      include HasCrud::ActiveRecord
    end
  end
end

app/models/koi/application_record.rb
# frozen_string_literal: true

module Koi
  class ApplicationRecord < ActiveRecord::Base
    include Koi::Model

    self.abstract_class = true
  end
end

app/controllers/koi/admin_crud_controller.rb
# frozen_string_literal: true

module Koi
  class AdminCrudController < Koi::ApplicationController
    KOI_PATH_HELPER_RE = /(\w+_|\b)koi_(\w+)_path$/.freeze

    helper :all
    has_crud admin: true
    defaults route_prefix: "admin"

    def index
      respond_to do |format|
        format.html
        format.js
        format.csv { respond_with_csv }
      end
    end

    protected

    def respond_to_missing?(key, include_private = false)
      KOI_PATH_HELPER_RE.match?(key) || super
    end

    # Matches missing route methods of the form (action_)?koi_(controller)_path,
    # and sends them to koi_engine instead.
    #
    # This is necessary because inherited_resources is resolving paths differently
    # depending on whether they belong to the koi_engine or not.
    #
    def method_missing(key, *sig, &blk)
      if (match = KOI_PATH_HELPER_RE.match(key))
        prefix, suffix = match.to_a.drop 1
        koi_engine.send :"#{prefix}#{suffix}_path", *sig, &blk
      else
        super
      end
    end
  end
end

app/controllers/koi/admin_resource_controller.rb
module Koi
  # Initialized by Koi::Resource::register
  class AdminResourceController < ActionController::Base
    layout 'koi/application'

    # See lib/koi/resource_actions.rb for actions
  end
end

app/controllers/koi/admins_controller.rb
# frozen_string_literal: true

module Koi
  class AdminsController < AdminCrudController
    defaults resource_class: AdminUser, route_prefix: ""

    def update_resource(object, attributes)
      if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
        object.update_without_password(*attributes)
      else
        object.update(*attributes)
      end
    end
  end
end

app/controllers/koi/alias_nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class AliasNavItemsController < NavItemsController
    defaults resource_class: AliasNavItem
  end
end

app/controllers/koi/application_controller.rb
# frozen_string_literal: true

module Koi
  class ApplicationController < ActionController::Base
    include HasCrud::ActionController
    include ExportableController

    helper :all
    layout :layout_by_resource
    before_action :authenticate_admin, except: :login
    before_action :set_navigation_menu, except: :login

    def login
      if admin_signed_in?
        redirect_to dashboard_path
      else
        redirect_to koi_engine.new_admin_session_path
      end
    end

    def clear_cache
      Rails.logger.warn("[CACHE CLEAR] - Cleaning entire cache manually by #{current_admin} request")
      Rails.cache.clear
      redirect_back(fallback_location: dashboard_path)
    end

    protected

    # FIXME: Hack to set layout for admin devise resources
    def layout_by_resource
      if devise_controller? && resource_name == :admin
        "koi/devise"
      else
        "koi/application"
      end
    end

    # FIXME: Hack to redirect back to admin after admin login
    def after_sign_in_path_for(resource_or_scope)
      resource_or_scope.is_a?(AdminUser) ? koi_engine.root_path : super
    end

    # FIXME: Hack to redirect back to admin after admin logout
    def after_sign_out_path_for(resource_or_scope)
      resource_or_scope == :admin ? koi_engine.root_path : super
    end

    def authenticate_admin
      redirect_to koi_engine.new_admin_session_path unless admin_signed_in?
    end

    def set_navigation_menu
      @navigation_menu = NavigationMenu.find_by(slug: "admin")
    end
  end
end

app/controllers/koi/assets_controller.rb
# frozen_string_literal: true

module Koi
  class AssetsController < AdminCrudController
    before_action :init

    layout "koi/assets"

    def index
      @assets = collection.newest_first.page(params[:page]).per(20)
      params[:asset] = { tag_list: [@tags] }
      super
    end

    def new
      @assets = collection.newest_first.page(params[:page]).per(20)
      params[:asset] = { tag_list: [@tags] }
      super
    end

    def show
      @assets = collection.newest_first.page(params[:page]).per(20)
    end

    def edit
      @assets = collection.newest_first.page(params[:page]).per(20)
    end

    def create
      super do |format|
        format.html { redirect_to resource_path(resource) }
        format.js { render plain: resource.id }
      end
    end

    def destroy
      super do |format|
        format.html { redirect_to new_resource_path }
        format.js
      end
    end

    # HELPERS ########################################################################################

    def redirect_path
      resource_path(resource)
    end

    def url_options
      super.reverse_merge(custom_url_options)
    end

    def custom_url_options
      @custom_url_options || {}
    end

    def custom_url_options=(options)
      @custom_url_options = (@custom_url_options || {}).merge(options) if options.is_a?(Hash)
    end

    protected

    def sort_column
      resource_class.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def collection
      return get_collection_ivar unless get_collection_ivar.nil?

      coll = end_of_association_chain
      coll = coll.unassociated
      coll = coll.search_data params[:search]
      coll = coll.tagged_with @tags if @tags.present?
      coll = coll.order "#{sort_column} #{sort_direction}"
      set_collection_ivar coll
    end

    def init
      @tags = params[:tags] || []
      @all_tags = resource_class.tag_counts_on(:tags).map(&:name)
      self.custom_url_options = { tags: @tags, CKEditorFuncNum: params[:CKEditorFuncNum] }
    end

    def create_resource(object)
      object.data = params[:file]
      object.data_name = params[:file].original_filename
      object.tag_list = params[:tag_list]
      object.save
    end
  end
end

app/controllers/koi/composable_contents_controller.rb
class Admin::PageContentsController < Koi::AdminCrudController
end

app/controllers/koi/composable_pages_controller.rb
module Koi
  class ComposablePagesController < AdminCrudController
  end
end

app/controllers/koi/crud_controller.rb
# frozen_string_literal: true

module Koi
  class CrudController < ActionController::Base # rubocop:disable Rails/ApplicationController
    include HasCrud::ActionController

    layout "application"
    has_crud
    defaults route_prefix: ""
  end
end

app/controllers/koi/documents_controller.rb
# frozen_string_literal: true

module Koi
  class DocumentsController < Koi::AssetsController
    defaults route_prefix: "", resource_class: Document

    def create
      create! do |success, failure|
        failure.html do
          logger.warn("[Asset Upload] - #{resource.errors.messages[:data].join(', ')}")
          render json: resource.errors, status: :unprocessable_entity
        end
        failure.js do
          logger.warn("[Asset Upload] - #{resource.errors.messages[:data].join(', ')}")
          render json: resource.errors, status: :unprocessable_entity
        end
        success.js { render plain: resource.id }
      end
    end
  end
end

app/controllers/koi/folder_nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class FolderNavItemsController < NavItemsController
    defaults resource_class: FolderNavItem
  end
end

app/controllers/koi/friendly_id_slugs_controller.rb
# frozen_string_literal: true

module Koi
  class FriendlyIdSlugsController < AdminCrudController
    defaults route_prefix: ""
  end
end

app/controllers/koi/images_controller.rb
# frozen_string_literal: true

module Koi
  class ImagesController < Koi::AssetsController
    defaults route_prefix: "", resource_class: Image
  end
end

app/controllers/koi/module_nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class ModuleNavItemsController < NavItemsController
    defaults resource_class: ModuleNavItem
  end
end

app/controllers/koi/nav_items_controller.rb
# frozen_string_literal: true

module Koi
  class NavItemsController < AdminCrudController
    defaults route_prefix: ""
    custom_actions resource: :toggle

    def new
      @site_parent = NavItem.find(params[:site_parent])
      super
    end

    def create
      create! do |success, failure|
        success.html { redirect_to redirect_path }
        success.js
        failure.js
      end
    end

    def update
      update! do |success, failure|
        success.html { redirect_to redirect_path }
        success.js
        failure.js
      end
    end

    def destroy
      destroy! do |format|
        format.html { redirect_to redirect_path }
        format.js
      end
    end

    def sitemap
      @nav_items = NavItem.all
    end

    def savesort
      nodes = JSON.parse params[:set]

      nodes.map! do |node|
        node.each_with_object({}) do |(key, val), hash|
          hash[key.to_sym] = ActiveRecord::Base.connection.quote val
        end.reverse_merge parent_id: "NULL" # in case of `undefined` in which update below will fail
      end

      ids = nodes.pluck(:id)

      # mass update (should be abstracted)
      NavItem.connection.execute <<-SQL
        UPDATE nav_items
          SET lft = CASE id
                      #{nodes.map { |node| 'WHEN %<id>s THEN %<lft>s' % node }.join "\n"}
                    END,
              rgt = CASE id
                      #{nodes.map { |node| 'WHEN %<id>s THEN %<rgt>s' % node }.join "\n"}
                    END,
              parent_id = CASE id
                      #{nodes.map { |node| 'WHEN %<id>s THEN %<parent_id>s' % node }.join "\n"}
                    END#{'                    '}
        WHERE id in (#{ids.join ','})
      SQL
      render partial: "nav_item", locals: { nav_item: RootNavItem.root, level: 0 }
    end

    def sort_children(element, dbitem)
      prevchild = nil
      element["children"].each do |child|
        childitem = NavItem.find(child["id"])
        prevchild.nil? ? childitem.move_to_child_of(dbitem) : childitem.move_to_right_of(prevchild)
        sort_children(child, childitem) unless child["children"].nil?
        prevchild = childitem
      end
    end

    def toggle
      resource.toggle_hidden!
      respond_to do |format|
        format.html { redirect_path }
        format.js
      end
    end

    protected

    def redirect_path
      if params[:commit].eql?("Continue")
        edit_resource_url
      else
        sitemap_nav_items_path
      end
    end
  end
end

app/controllers/koi/navigation_links_controller.rb
# frozen_string_literal: true

module Koi
  class NavigationLinksController < Koi::ApplicationController
    before_action :set_menu
    before_action :set_link, except: %i[index new create]

    def index
      render locals: { links: @menu.navigation_links }
    end

    def new
      render locals: { link: @menu.navigation_links.build }
    end

    def create
      link = @menu.navigation_links.build(navigation_link_params)
      if link.save
        render :update, locals: { link: link, previous: NavigationLink.new }, notice: "Navigation link created"
      else
        render :new, status: :unprocessable_entity, locals: { link: link }
      end
    end

    def show; end

    def edit
      render locals: { link: @link }
    end

    # PATCH /admins/navigation_menu/:slug/navigation_link/:id
    def update
      @link.attributes = navigation_link_params

      if @link.valid?
        previous = @link
        @link    = @link.dup.tap(&:save!)
        render locals: { link: @link, previous: previous }, notice: "Navigation link updated"
      else
        render :edit, status: :unprocessable_entity, locals: { link: @link }
      end
    end

    private

    def navigation_link_params
      params.require(:navigation_link).permit(%i[title url visible new_tab])
    end

    def set_menu
      @menu = NavigationMenu.find_by!(slug: params[:navigation_menu_id])
    end

    def set_link
      @link = NavigationLink.find(params[:id])
    end
  end
end

app/controllers/koi/navigation_menus_controller.rb
class Koi::NavigationMenusController < Koi::ApplicationController
  include Katalyst::Tables::Backend

  def index
    sort, menus = table_sort(NavigationMenu.all)

    render locals: { menus: menus, sort: sort }
  end

  def new
    render locals: { menu: NavigationMenu.new }
  end

  def create
    menu = NavigationMenu.new(navigation_menu_params)

    if menu.save
      redirect_to menu, notice: "Navigation menu created"
    else
      render :new, locals: { menu: menu }, status: :unprocessable_entity
    end
  end

  def show
    menu = NavigationMenu.find_by!(slug: params[:id])

    render locals: { menu: menu }
  end

  # PATCH /admins/navigation_menus/:slug
  def update
    menu = NavigationMenu.find_by!(slug: params[:id])

    menu.attributes = navigation_params

    unless menu.valid?
      return render :show, locals: { menu: menu }, status: :unprocessable_entity
    end

    case params[:commit]
    when "publish"
      menu.save!
      menu.publish!
    when "save"
      menu.save!
    when "revert"
      menu.revert!
    end
    redirect_to menu
  end

  def destroy
    menu = NavigationMenu.find_by!(slug: params[:id])

    menu.destroy!

    redirect_to navigation_menus_path, notice: "Navigation menu destroyed"
  end

  private

  def navigation_menu_params
    params.require(:navigation_menu).permit(:title, :slug)
  end

  def navigation_params
    return {} if params[:navigation_menu].blank?

    params.require(:navigation_menu)
          .permit(navigation_links_attributes: [:id, :index, :depth])
  end
end

app/views/koi/navigation_menus/_add_navigation_link.html.erb
<%= tag.div draggable: true,
            data:      {
              turbo_frame: "navigation-editor-form",
              controller:  "new-editable-item",
              action:      <<~ACTIONS,
                  dragstart->new-editable-item#dragstart
              ACTIONS
            },
            class:     "button__primary add-new-menu-link" do %>
  <svg>
    <use xlink:href="#icon-drag"/>
  </svg>

  Drag to place new link

  <template data-new-editable-item-target="template">
    <%= render "koi/navigation_menus/navigation_menu_link", link: item %>
  </template>
<% end %>

<%# When rendering new link, removes all incomplete "new" items %>
<%= turbo_stream.replace dom_id(item) do %>
  <div id="<%= dom_id(item) %>" class="link-item" data-controller="navigation-editor-item" data-delete>
  </div>
<% end %>

app/views/koi/navigation_menus/_link_item.html.erb
<div id="<%= dom_id(link) %>" class="link-item" data-controller="navigation-editor-item">
  <div class="tree">
    <div class="list-actions collapse-actions">
      <%= button_tag class: "navigation-editor--item--collapse tooltip", data: { action: "navigation#collapse" } do %>
        <svg class="icon icon-collapse">
          <use xlink:href="#icon-collapse"/>
        </svg>
        <span class="tooltip-text">Collapse tree</span>
      <% end %>

      <%= button_tag class: "navigation-editor--item--expand tooltip", data: { action: "navigation#expand" } do %>
        <svg class="icon icon-expand">
          <use xlink:href="#icon-expand"/>
        </svg>
        <span class="tooltip-text">Expand tree</span>
      <% end %>
    </div>

    <div class="navigation-menu-link-icon <%= link.url.present? ? "link-icon" : "title-icon" %> <%= "invisible-icon" unless link.visible? %>"></div>
    <h4 class="title" title="<%= link.title %>"><%= link.title %></h4>
    <% unless link.visible? %>
      <%= icon("hidden", width: "16px", height: "16px") %>
    <% end %>
  </div>

  <%= link_to link.url || "", link.url || "", class: "url" %>

  <div class="list-actions">
    <%= button_tag class: "navigation-editor--item--de-nest tooltip", data: { action: "navigation#deNest" } do %>
      <svg class="icon icon-de-nest">
        <use xlink:href="#icon-de-nest"/>
      </svg>
      <span class="tooltip-text">Move in</span>
    <% end %>

    <%= button_tag class: "navigation-editor--item--nest tooltip", data: { action: "navigation#nest" } do %>
      <svg class="icon icon-nest">
        <use xlink:href="#icon-nest"/>
      </svg>
      <span class="tooltip-text">Move out</span>
    <% end %>

    <%= link_to link.persisted? ? edit_navigation_menu_link_path(link.navigation_menu, link) : new_navigation_menu_link_path(link.navigation_menu, link),
                class: "navigation-editor--item--edit tooltip",
                data:  { turbo_frame: "navigation-editor-form" } do %>
      <svg class="icon icon-edit">
        <use xlink:href="#icon-edit"/>
      </svg>
      <span class="tooltip-text">Edit</span>
    <% end %>

    <%= button_tag class: "navigation-editor--item--delete tooltip", data: { action: "navigation#remove" } do %>
      <svg class="icon icon-delete">
        <use xlink:href="#icon-delete"/>
      </svg>
      <span class="tooltip-text">Delete</span>
    <% end %>
  </div>

  <%= fields("navigation_menu[navigation_links_attributes][]", model: link, index: nil, skip_default_ids: true) do |form| %>
    <%= form.hidden_field :id %>
    <%= form.hidden_field :depth, data: { navigation_depth_input: true } %>
    <%= form.hidden_field :index, data: { navigation_index_input: true } %>
  <% end %>
</div>

app/views/koi/navigation_menus/_navigation_editor_index.html.erb
<%= turbo_frame_tag "navigation-editor-form" do %>
  <%= render partial: "koi/navigation_menus/add_navigation_link", collection: new_items_for_navigation(menu), as: :item %>
<% end %>

app/views/koi/navigation_menus/_navigation_menu_link.html.erb
<li class="navigation-menu-link"
    draggable="true"
    role="treeitem"
    data-navigation-item
    data-navigation-index="<%= link.index %>"
    data-navigation-depth="<%= link.depth %>"
    data-deny-de-nest
    data-deny-nest
    data-deny-collapse
    data-deny-expand
    data-deny-delete
    data-deny-drag
    data-deny-edit>
  <%= render "koi/navigation_menus/link_item", link: link %>
</li>

app/views/koi/navigation_menus/index.html.erb
<% content_for :title, "Navigations" %>

<nav class="index-table-actions">
  <div class="item-actions">
    <%= link_to "Add", new_navigation_menu_path, class: "button__primary" %>
  </div>
</nav>

<%= table_with collection: menus, sort: sort, class: "index-table" do |row, menu| %>
  <%= row.cell :title do |cell| %>
    <%= link_to cell.value, navigation_menu_path(menu) %>
  <% end %>
  <%= row.cell :slug %>
  <%= row.cell :actions do |cell| %>
    <%= button_to "Delete", navigation_menu_path(menu), method: :delete %>
  <% end %>
<% end %>

app/views/koi/navigation_menus/new.html.erb
<% content_for :title, "New navigation" %>
<% content_for(:breadcrumbs) { link_to "Navigations", navigation_menus_path } %>
<% content_for :form_class, "govuk-forms" %>

<%= form_with model: menu, builder: GOVUKDesignSystemFormBuilder::FormBuilder do |form| %>
  <%= form.govuk_text_field :title %>
  <%= form.govuk_text_field :slug %>
  <%= form.govuk_submit %>
<% end %>

app/views/koi/navigation_menus/show.html.erb
<% content_for :title, menu.title %>
<% content_for(:breadcrumbs) { link_to "Navigations", navigation_menus_path } %>
<% content_for :layout_class, "collapse-header-spacing extra-side-spacing" %>
<% content_for :form_class, "govuk-forms" %>
<% content_for :layout_controller, "edit" %>
<% content_for :layout_action, "change->edit#change" %>

<%= version_status_bar(menu, form_id: dom_id(menu)) %>

<div class="navigation-menu-columns">

  <%= form_with(model:  menu,
                id:     dom_id(menu),
                method: :patch,
                class:  "navigation-editor navigation-menu",
                html:   { role: "tree" },
                data:   { controller: "navigation", action: "submit->navigation#reindex" }) do |form| %>

    <div class="navigation-menu-header">
      <div class="link-item">
        <div class="indentation">
          <h4 class="heading-four">Title</h4>
        </div>
        <h4 class="heading-four">Url</h4>
        <h4 class="heading-four actions">Actions</h4>
      </div>
    </div>

    <%# a hidden field to ensure that even if there are no links we will still receive form data %>
    <%= fields("navigation_menu[navigation_links_attributes][]", model: NavigationLink.new, index: nil, skip_default_ids: true) do |form| %>
      <%= form.hidden_field :id %>
    <% end %>

    <%= editable_list id: dom_id(menu, :links), data: { navigation_target: "menu", action: "reindex->navigation#reindex reset->navigation#reset" } do %>
      <%= render partial: "navigation_menu_link", collection: menu.latest_navigation_links || [], as: :link %>
    <% end %>
  <% end %>
</div>

<%= content_for :side_top do %>
  <aside>
    <%= render "koi/navigation_menus/navigation_editor_index", menu: menu %>
  </aside>
<% end %>